/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal

 # This is written by rahul: 
  this is given by them I just made changes or write some code.
  const express = require('express');
  const bodyParser = require('body-parser');
  
  const app = express();
  
  app.use(bodyParser.json());
  
  module.exports = app;
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs");
const app = express();
// const PORT = 3000;
const zod = require("zod");
const { title } = require("process");

//how to write zod schema
// const schema = zod.object({
//   title: zod.string({
//     required_error: "Title is required field!!!",
//   }),
//   completed: zod.boolean(),
//   description: zod.string({
//     required_error: "Description is required field!!!",
//   }),
// });

app.use(bodyParser.json());

app.get("/todos", (req, res) => {
  try {
    let todoList = [];
    fs.readFile("todos.json", function (err, data) {
      if (err) {
        throw err;
      }
      todoList = JSON.parse(data);
      // console.log('todoList', todoList);
      if (todoList.length > 0) {
        return res
          .status(200)
          .json(todoList);
      }
    });
  } catch (error) {
    console.log(error);
    res.status(500).json({ error: error.response.data.error });
  }
});

app.post("/todos", (req, res) => {
  try {
    let todoDetails = {
      id: Math.floor(Math.random() * 1000000),
      title: req.body.title,
      description: req.body.description,
      completed: req.body.completed,
    };
    // const response = schema.safeParse(todoDetails);

    let todolist = [];

    fs.readFile("todos.json", "utf-8", function (err, data) {
      if (err) {
        throw err;
      }
      todolist = JSON.parse(data);
      todolist.push(todoDetails);
      if (todolist.length > 0) {
        fs.writeFile("todos.json", JSON.stringify(todolist), (err) => {
          if (err) {
            throw err;
          }
          return res
            .status(201)
            .send(todoDetails);
        });
      }
    });
  } catch (error) {
    console.log(error);
    return res.status(500).json({ error: error });
  }
});

app.get("/todos/:id", (req, res) => {
  const id = req.params.id;
  let todoSpecificObj;
  let todolist;
  fs.readFile("todos.json", "utf-8", function (err, data) {
    if (err) {
      throw err;
    }
    todolist = JSON.parse(data);
    todoSpecificObj = todolist.find((item) => item.id == id);
    
    if (todoSpecificObj) {
      return res.status(200).send(JSON.stringify(todoSpecificObj) );
    }
    return res.status(404).send();
  });
});

app.put("/todos/:id", (req, res) => {
  const body = req.body;
  const id = req.params.id;
  let todolist;
  fs.readFile("todos.json", "utf-8", function (err, data) {
    if (err) {
      throw err;
    }
    todolist = JSON.parse(data);

    for (let i = 0; i < todolist.length; i++) {
      if (todolist[i]["id"] == id) {
        if (body.title) {
          todolist[i]["title"] = body.title;
        }
        if (body.completed) {
          todolist[i]["completed"] = body.completed;
        }
        if (body.description) {
          todolist[i]["description"] = body.description;
        }
        break;
      }
    }

    fs.writeFile("todos.json", JSON.stringify(todolist), function (err) {
      if (err) {
        throw err;
      }
      return res.status(200).json({ success: "successfully updated..." });
    });
  });
});

app.delete("/todos/:id", (req, res) => {
  const id = req.params.id;
  let todolist;
  fs.readFile("todos.json", "utf-8", function (err, data) {
    if (err) {
      throw err;
    }
    todolist = JSON.parse(data);
    let updatedTodolist = todolist.filter((item) => item.id != id);
    fs.writeFile("todos.json", JSON.stringify(updatedTodolist), function (err) {
      if (err) {
        throw err;
      }
      return res
        .status(200)
        .json({ success: "Deleted the item successfully..." });
    });
  });
});

app.all("*", function (req, res) {
  throw new Error("Bad request");
});

app.use((e, req, res, next) => {
  if (e.message === "Bad request") {
    // console.log("some: ",e)
    return res.status(404).json({ error: e.message });
  }
});

// app.listen(3000, () => {
//   console.log("server connected");
// });

module.exports = app;
